KEYWORDS = {
    "Mathematics": [
        "Linear Algebra and Calculus",
        "Vector Calculus, Differential Equations and Transforms",
        "Partial Differential Equation and Complex Analysis",
        "Probability, Random Process",
        "Probability, Statistics and Numerical Methods",
        "Discrete Mathematical Structures",
        "Graph Theory",
        "Topology",
        "Fuzzy Sets & Neural Networks",
        "Formal Languages and Automata Theory",
        "Discrete Mathematics",
        "Introductory Topics in Statistics, Probability and Calculus",
        "Statistical Methods",
        "Computational Statistics",
        "Probability, Random Processes and Numerical Methods",
        "Statistical Foundations for Data Science",
        "Principles of Object Oriented Techniques",
        "Operations Research",
        # Electives
        "Number Theory and Abstract Algebra",
        "Applied Linear Algebra",
        "Stochastic Processes for Data Science",
        "Matrix Analysis",
        "Multivariate Data Analysis",
        "Mathematical Economics",
        "Dynamical Systems and Data Science",
        "Advanced Mathematics",
        "Advanced Optimization Techniques",
        "Descriptive Statistics",
        "Topological Data Analysis",
        "Operational Research and Queuing Theory",
        "Genetic Algorithm",
        "Optimization Techniques",
        "Numerical Methods in Data Science",
        "Fuzzy Set Theory and Applications",
        "Optimization and Metaheuristics",
        "Probabilistic and Stochastic Modelling",
        "Advanced Computational Methods",
        "Optimisation Techniques in Civil Engineering",
        "Optimization Techniques and Applications",
        "Decisions with Metaheuristics",
    ],
    "Computer Science": [
        "Programming in C",
        "Data Structures",
        "Algorithm Analysis and Design",
        "Operating Systems",
        "Database Management Systems",
        "Computer Networks",
        "Artificial Intelligence",
        "Machine Learning",
        "Compiler Design",
        "Computer Graphics and Image Processing",
        "Distributed Computing",
        "Object Oriented Programming",
        "Software Engineering",
        "Computer Organization and Architecture",
        "Data Science",
        "Internetworking with TCP/IP",
        "Web Application Development",
        "Cryptography and Network Security",
        "Problem Solving Using Python",
        "Digital System Design",
        "Logic System Design",
        "System Software",
        "Microprocessors and Microcontrollers",
        "Computer Vision",
        "Data Analytics",
        "Big Data Analytics",
        "Text Mining",
        "Information Security",
        "Design and Analysis of Algorithms",
        "Fundamentals of Computer Science",
        "Object Oriented Programming Using Java",
        "Operating System Concepts",
        "Data Communication and Networking",
        "Data Warehousing and Data Mining",
        "Computer Organisation and Architecture",
        "Logic Circuit Design",
        "Scientific Computing",
        "Software Design with UML",
        "IT Project Management",
        "Usability Design of Software Applications",
        "Services Science and Service Operational Management",
        "Data Structures & Algorithms",
        "Computational Complexity",
        # Electives
        "Data Visualization",
        "Blockchain & Cybersecurity",
        "Cloud Computing",
        "Deep Learning",
        "Semantic Web",
        "Social Network Analysis",
        "Algorithmic Game Theory",
        "Genetic Algorithm",
        "Soft Computing",
        "Bioinformatics",
        "Natural Language Processing",
        "Internet of Things",
        "High Performance Computing",
        "Parallel Computing",
        "Data Mining",
        "Mobile Computing",
        "Computational Linguistics",
        "Programming Paradigms",
        "Client Server Architecture",
        "Data Compression Techniques",
        "Software Testing",
        "Foundations of Machine Learning",
        "Foundations of Security in Computing",
        "Security in Computing",
        "Automated Verification",
        "Model Based Software Development",
        "Introduction to IA32 Architecture",
        "Advanced Topics in IA32 Architecture",
        "Unified Extended Firmware Interface",
        "Web Programming",
        "Programming in Python",
        "Data and Computer Communication",
        "Information Retrieval",
        "Content Based Retrieval",
        "Cognitive Analytics",
        "Speech Systems",
        "AI & Robotics",
        "Distributed Systems",
        "Object Oriented Modeling and Design",
        "Advanced Database Management Systems",
        "Search Engine Optimisation",
        "Computer Graphics",
        "Pipelining and Parallel Processing",
        "Network Science",
        "Information Storage Management",
        "Software Quality Assurance",
        "Software Architecture",
        "Network on Chips",
        "Conversational Systems",
        "Cloud, Microservices & Application",
        "Modern Web Applications",
        "Introduction to IoT",
        "Advanced Social, Text and Media Analytics",
        "Computational Finance and Modeling",
        "Image Processing and Pattern Recognition",
        "Robotics and Embedded Systems",
        "Quantum Computation & Quantum Information",
        "Enterprise Systems",
        "Formal Methods and Tools in Software Engineering",
        "Blockchain Technologies",
        "Image Processing Technique",
        "ANN and Deep Learning",
        "Compiler Design",
        "Digital Image Processing",
        "Cyber and Network Forensics",
        "Data Mining and Warehousing",
        "High Speed Networks",
        "Adhoc and Wireless Sensor Networks",
        "Human Computer Interfacing",
        "Information Theory and Coding",
        "Big Data for IoT",
        "User Interface and User Experience Design",
        "Embedded Systems",
    ],
    "Electronics": [
        "Basics of Electrical and Electronics Engineering",
        "Analog Circuits",
        "Digital Signal Processing",
        "Power Electronics",
        "VLSI Circuit Design",
        "Communication Engineering",
        "Solid State Devices",
        "Network Theory",
        "Measurements and Instrumentation",
        "Control Systems",
        "Industrial Instrumentation",
        "Computer Architecture and Embedded Systems",
        "Analog Integrated Circuits",
        "Process Dynamics and Control",
        "Signals and Systems",
        "Circuits and Networks",
        "Analog Electronics",
        "DC Machines and Transformers",
        "Electromagnetic Theory",
        "Digital Electronics",
        "Power Systems I",
        "Synchronous and Induction Machines",
        "Linear Control Systems",
        "Advanced Control Systems",
        "Electrical System Design and Estimation",
        "Linear Integrated Circuits",
        "Analog and Digital Communication",
        "Electromagnetics",
        "Information Theory and Coding",
        "Microwaves and Antennas",
        "Wireless Communication",
        "Principles of Electronics",
        "Principles of Electrical Engineering",
        "Computer Architecture and Microcontrollers",
        "Logic Circuit Design",
        "Transducers and Measurements",
        # Electives
        "Embedded Systems",
        "Digital System Design",
        "Optoelectronic Devices",
        "FPGA Based System Design",
        "Speech and Audio Processing",
        "Wireless Sensor Networks",
        "Nanoelectronics",
        "Integrated Optics and Photonic Systems",
        "Industrial Drives and Control",
        "Control of Power Converters",
        "Aviation Electronics",
        "Digital Control System",
        "Power Plant Instrumentation",
        "MEMS",
        "Mechatronics",
        "Automotive Electronics",
        "Cyber Security",
        "Instrumentation and Control for Petrochemical Industries",
        "Optical Instrumentation",
        "Renewable Energy Technology",
        "Biomedical Instrumentation",
        "Electric Drives",
        "Nonlinear Systems",
        "Electric and Hybrid Vehicles",
        "Renewable Energy Systems",
        "Modern Operating Systems",
        "Smart Grid Technologies",
        "Power Quality",
        "Energy Storage Systems",
        "High Voltage Engineering",
        "Switched Mode Power Converters",
        "Design of Power Electronic Systems",
        "Solar PV Systems",
        "Industrial Instrumentation and Automation",
        "Optical Fiber Communication",
        "Satellite Communication",
        "Real Time Operating Systems",
        "Secure Communication",
        "Microwave Devices and Circuits",
        "Low Power VLSI",
        "Organic Electronics",
        "High Voltage Direct Current (HVDC) and FACTS",
        "Advanced Electronic Design",
        "Robust and Adaptive Control",
        "Adaptive Signal Processing",
        "Mixed Signal Circuit Design",
        "Analog CMOS Design",
        "RF Circuit Design",
        "DSP Architectures",
        "Nonlinear and Adaptive Control Systems",
        "SCADA and Distributed Control System",
        "Electromagnetic Interference and Compatibility",
        "Python for Signal and Image Processing",
        "Computer Numerical Control",
        "Data Structures and Algorithms",
        "Power Electronics",
        "Data Analysis",
        "Instrumentation",
        "Error Control Codes",
        "Introduction to MEMS",
        "Quantum Computing",
        "Modern Communication Systems",
        "Opto-Electronic Devices",
        "Pattern Recognition",
        "Entrepreneurship",
        "Computer Organization",
        "Material Science",
        "Illumination Technology Systems",
        "Digital Protection of Power",
        "Electrical Machine Design",
        "Computer Aided Power System Analysis",
        "Special Electric Machines",
        "Computer Networks",
        "Big Data Analytics",
    ],
    "Civil Engineering": [
        "Basics of Civil and Mechanical Engineering",
        "Engineering Mechanics",
        "Mechanics of Solids",
        "Fluid Mechanics and Hydraulics",
        "Surveying and Geomatics",
        "Engineering Geology",
        "Transportation Engineering",
        "Design of Concrete Structures",
        "Geotechnical Engineering",
        "Hydrology and Water Resources Engineering",
        "Construction Technology and Management",
        "Structural Analysis",
        "Environmental Engineering",
        "Design of Hydraulic Structures",
        "Design of Steel Structures",
        "Quantity Surveying & Valuation",
        # Electives
        "Advanced Computational Methods",
        "Geotechnical Investigation",
        "Traffic Engineering and Management",
        "Mechanics of Fluid Flow",
        "Advanced Concrete Technology",
        "Environmental Impact Assessment",
        "Functional Design of Buildings",
        "Prestressed Concrete",
        "Ground Improvement Techniques",
        "Highway Materials and Design",
        "Applied Hydrology",
        "Construction Planning and Management",
        "Advanced Environmental Engineering",
        "Optimisation Techniques in Civil Engineering",
        "Advanced Structural Design",
        "Geo-environmental Engineering",
        "Railway and Tunnel Engineering",
        "Irrigation and Drainage Engineering",
        "Construction Methods & Equipment",
        "Air Quality Management",
        "Urban Planning and Architecture",
        "Bridge Engineering",
        "Advanced Foundation Design",
        "Transportation Planning",
        "Informatics for Infrastructure Management",
        "Repair and Rehabilitation of Buildings",
        "Environmental Remote Sensing",
        "Building Services",
        "Earthquake Resistant Design",
        "Soil Structure Interaction",
        "Airport, Seaport and Harbour Engineering",
        "Hydroclimatology",
        "Sustainable Construction",
        "Climate Change and Sustainability",
        "Building Information Modelling",
    ],
    "Mechanical Engineering": [
        "Engineering Graphics",
        "Mechanics of Fluids",
        "Metallurgy and Material Science",
        "Engineering Thermodynamics",
        "Manufacturing Process",
        "Fluid Machinery",
        "Mechanics of Machinery",
        "Thermal Engineering",
        "Industrial and Systems Engineering",
        "Machine Tools and Metrology",
        "Heat and Mass Transfer",
        "Dynamics and Design of Machinery",
        "Advanced Manufacturing Engineering",
        "Design of Machine Elements",
        "Mechatronics",
        # Electives
        "Nondestructive Testing",
        "Computational Fluid Dynamics",
        "Advanced Mechanics of Solids",
        "IC Engines, Combustion and Pollution",
        "Automobile Engineering",
        "Product Design and Development",
        "Advanced Metal Joining Techniques",
        "Advanced Methods in Nondestructive Testing",
        "Optimization Techniques and Applications",
        "Finite Element Method",
        "Aerospace Engineering",
        "Hybrid and Electric Vehicles",
        "Operations Management",
        "Air Conditioning and Refrigeration",
        "Quality Management",
        "Decisions with Metaheuristics",
        "Pressure Vessel and Piping Design",
        "Data Analytics for Engineers",
        "Industrial Tribology",
        "Micro and Nano Manufacturing",
        "Heating and Ventilation Systems",
        "Composite Materials",
        "Artificial Intelligence and Machine Learning",
        "Heat Transfer Equipment Design",
        "Robotics and Automation",
        "Technology Management",
        "Cryogenic Engineering",
        "Reliability Engineering",
        "Industrial Internet of Things",
        "Acoustics and Noise Control",
        "Gas Turbines and Jet Propulsion",
        "New and Renewable Energy Engineering",
        "Additive Manufacturing",
        "Fracture Mechanics",
        "Power Plant Engineering",
    ],
    "Physics": [
        "Engineering Physics",
        "Physics for Computing Science",
    ],
    "Chemistry": ["Engineering Chemistry"],
    "Management": [
        "Life Skills",
        "Professional Communication",
        "Industrial Economics and Foreign Trade",
        "Management for Engineers",
        "Management for Software Engineers",
        "Industrial and Systems Engineering",
        "Fundamentals of Management",
        "Business Strategy",
        "Financial and Cost Accounting",
        "Financial Management",
        "Human Resource Management",
        "Marketing Research and Marketing Management",
        "Introduction to Innovation, IP Management & Entrepreneurship",
        "Design Thinking",
        "Management of Software Systems",
        "Business Communication and Value Science",
        "Construction Technology and Management",
        "Operations Management",
        "Technology Management",
        "Industrial Economics & Foreign Trade",
        "Trade",
        # Electives
        "Behavioral Economics",
        "Advance Finance",
        "Enterprise Systems",
        "Computational Finance and Modeling",
        "Quality Management",
        "Entrepreneurship",
    ],
    "Ethics and Society": [
        "Professional Ethics",
        "Sustainable Engineering",
        "Constitution of India",
        "Disaster Management",
        "Industrial Safety Engineering",
        "Design and Engineering",
        "Essence of Indian Traditional Knowledge",
        "Environmental Sciences",
    ],
}
