# Example categories
CATEGORIES = [
    "finance",
    "legal",
    "technical",
    "marketing",
    "general",
    "hr",
    "computer_science",
]
KEYWORDS = {
    "finance": ["budget", "cost", "revenue", "financial", "investment"],
    "legal": ["agreement", "contract", "compliance", "regulation", "legal"],
    "technical": ["api", "software", "database", "architecture", "code"],
    "marketing": ["campaign", "brand", "customer", "market", "promotion"],
    "hr": ["employee", "recruitment", "training", "benefits", "performance"],
    "computer_science": [
        # Core CS foundations
        "algorithm",
        "data structure",
        "computational complexity",
        "big o notation",
        "recursion",
        "sorting",
        "searching",
        "graph theory",
        "tree",
        "hash table",
        # Programming concepts
        "object oriented programming",
        "functional programming",
        "inheritance",
        "polymorphism",
        "encapsulation",
        "abstraction",
        "design patterns",
        "mvc",
        # Languages
        "java",
        "python",
        "c++",
        "javascript",
        "typescript",
        "rust",
        "go",
        "c#",
        # Databases
        "sql",
        "nosql",
        "database design",
        "entity relationship",
        "normalization",
        "acid",
        "indexing",
        "query optimization",
        "mongodb",
        "postgresql",
        # Web development
        "html",
        "css",
        "dom",
        "rest api",
        "frontend",
        "backend",
        "full stack",
        "http",
        "https",
        "authentication",
        "authorization",
        "jwt",
        "oauth",
        # Operating systems
        "operating system",
        "process management",
        "memory management",
        "file system",
        "virtualization",
        "kernel",
        "threading",
        "concurrency",
        "deadlock",
        "race condition",
        # Networks
        "networking",
        "tcp/ip",
        "dns",
        "routing",
        "protocol",
        "socket programming",
        "client server",
        "distributed systems",
        "peer to peer",
        "cloud computing",
        # Security
        "cybersecurity",
        "cryptography",
        "encryption",
        "hashing",
        "authentication",
        "authorization",
        "vulnerability",
        "exploit",
        "penetration testing",
        # AI/ML related
        "artificial intelligence",
        "machine learning",
        "neural network",
        "deep learning",
        "nlp",
        "computer vision",
        "reinforcement learning",
        # Software engineering
        "agile",
        "scrum",
        "devops",
        "ci/cd",
        "version control",
        "git",
        "testing",
        "debugging",
        "requirements",
        "documentation",
        "code review",
        "refactoring",
    ],
}
